### PR TITLE
FEAT: Added the Utility Classes and Variables

### PR DESCRIPTION
**Pull request by VishalPatil18**

### CODE REVIEW

**Comment by Kevin-Solomon** [comment]
Looks amazing Vishal !!

**Review by Kevin-Solomon — APPROVED** [review]
Looks good vishal

**Review by ajitpsakri — APPROVED** [review]

**Comment by Sudhanshusoni45** [comment]
Everything Looks Good Vishal, just one thing you have used !important in box shadow variable just see if you can avoid using that.

**Review by Sudhanshusoni45 — COMMENTED** [review]
Everything Looks Good Vishal, just one thing you have used !important in box shadow variable just see if you can avoid using that.

**Pull request merged**
