### PR TITLE
FEAT: Added the Input and List Components

### PR DESCRIPTION
**Pull request by VishalPatil18**
Added the Input and List components having various varients.

Screenshots:
PS. The original size of elements may vary as these are just screenshots
Screenshot 2022-01-28 at 22 31 07
Screenshot 2022-01-28 at 22 31 17
Screenshot 2022-01-29 at 00 20 31

Screenshot 2022-01-28 at 22 31 38
Screenshot 2022-01-28 at 22 31 50
Screenshot 2022-01-28 at 22 32 00
Screenshot 2022-01-28 at 22 32 18

### CODE REVIEW

**Review by kart-c — CHANGES_REQUESTED** [review]
Your _list.html file has `alt` attribute missing in the `img` tags. Other than that everything else looks great

**Comment by VishalPatil18** [comment]
> Your _list.html file has `alt` attribute missing in the `img` tags. Other than that everything else looks great

Sure I'll add those. Thanks for the suggestion 👍

**Comment by VishalPatil18** [comment]
> Your _list.html file has `alt` attribute missing in the `img` tags. Other than that everything else looks great

Hey Kartikeya, I've made all the suggested changes. Please review those once. Thank You!

**Review by AtulPant2704 — APPROVED** [review]

**Review by kart-c — APPROVED** [review]
👍 looks good Vishal. Your code is really clean

**Pull request merged**
